SELECT
    a.O_ORDERKEY AS ORDER_ID,
    a.O_CUSTKEY AS CUSTOMER_ID,
    a.O_ORDERDATE AS ORDER_DATE,
    DATEADD(DAY, 20, a.O_ORDERDATE) AS TRANSACTION_DATE,
    TO_NUMBER(RPAD(CONCAT(a.O_ORDERKEY, a.O_CUSTKEY, TO_CHAR(a.O_ORDERDATE, 'YYYYMMDD')), 24, '0')) AS TRANSACTION_NUMBER,
    a.O_TOTALPRICE AS AMOUNT,
    CAST(
        CASE ABS(MOD(RANDOM(1), 2)) + 1
            WHEN 1 THEN 'DR'
            WHEN 2 THEN 'CR'
        END AS VARCHAR(2)
    ) AS TYPE
FROM {{ source('tpch_sample', 'ORDERS') }} AS a
WHERE a.O_ORDERDATE = TO_DATE('{{ var('load_date') }}')
